
name: Load Model and Use It

on:
  workflow_run:
    workflows: ["AutomateModelTraining"]  # Must match the name of your training workflow
    types:
      - completed

jobs:
  load-and-use:
    runs-on: ubuntu-latest
    needs: train-and-upload
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: store  # specify a folder to store the artifact

      - name: Load and use model
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python main.py